doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'

        driver_class: App\Doctrine\DBAL\Driver\PDO\SQLSrv\Driver
        host: 148.206.141.235
        port: 2011
        user: rdtijpaa00
        password: KsjEWertyVT4-62
        dbname: aabdd02
        charset: roman8
        types:
            float: App\Doctrine\DBAL\FloatType
            money: App\Doctrine\DBAL\MoneyType
            date: App\Doctrine\DBAL\DateType
            string: App\Doctrine\DBAL\StringType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App

        dql:
            numeric_functions:
                rand: App\Doctrine\DQL\Rand