<?php

namespace App\Utils;

class Disciplina {    

    const FISICA = "FISICA";
    const MATEMATICAS = "MATEMATICAS";
    const QUIMICA = "QUIMICA";

    const BIOMEDICA = "BIOMEDICA";
    const COMPUTACION = "COMPUTACION";
    const INGENIERIA = "INGENIERIA";

    const AGRONOMIA = "AGRONOMIA";
    const BIOLOGIA = "BIOLOGIA";
    const BIOTECNOLOGIA = "BIOTECNOLOGIA";

    const INGENIERIA_AGRONOMICA = "INGENIERIA AGRONOMICA";
    const MEDICINA_VETERINARIA_Y_ZOOTECNIA = "MEDICINA VETERINARIA Y ZOOTECNIA";
    const QUIMICA_FARMACEUTICA_BIOLOGICA = "QUIMICA FARMACEUTICA BIOLOGICA";

    const CIENCIAS_BIOMEDICAS = "CIENCIAS BIOMEDICAS";
    const ENFERMERIA = "ENFERMERIA";
    const ESTOMATOLOGIA = "ESTOMATOLOGIA";
    const MEDICINA = "MEDICINA";
    const NUTRICION = "NUTRICION";
    const ANTROPOLOGIA = "ANTROPOLOGIA";
    const POLITICA = "POLITICA";
    const PSICOLOGIA = "PSICOLOGIA";
    const SOCIOLOGIA = "SOCIOLOGIA";
    const ADMINISTRACION = "ADMINISTRACION";
    const ECONOMIA = "ECONOMIA";
    const FINANZAS = "FINANZAS";

    const ARTES = "ARTES";
    const CIENCIAS_DE_LA_COMUNICACION = "CIENCIAS DE LA COMUNICACION";
    const COMUNICACION = "COMUNICACION";
    const DERECHO = "DERECHO";
    const FILOSOFIA = "FILOSOFIA";
    const HISTORIA = "HISTORIA";
    const LENGUAS_EXTRANJERAS = "LENGUAS EXTRANJERAS";
    const LINGUISTICA = "LINGÜISTICA";
    const LITERATURA = "LITERATURA";

    const INGENIERIA_DE_LOS_ALIMENTOS = "INGENIERIA DE LOS ALIMENTOS";
}